package fr.antoinehory.divination.data.database.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import fr.antoinehory.divination.data.model.GameType
import java.util.Date

/**
 * Represents a log entry for a game launch or play event.
 * This entity is stored in the "launch_logs" table in the database.
 *
 * @property id The unique identifier for the log entry. Auto-generated by the database.
 * @property gameType The [GameType] of the game that was played.
 * @property result A string representation of the outcome of the game play.
 *                  The format of this string can vary depending on the [gameType].
 * @property timestamp The [Date] and time when the game play event occurred.
 *                     Defaults to the current date and time when the log is created.
 */
@Entity(tableName = "launch_logs")
data class LaunchLog(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val gameType: GameType,
    val result: String,
    val timestamp: Date = Date()
)