package fr.antoinehory.divination.data.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverters
import fr.antoinehory.divination.data.database.util.DiceConfigListConverter

/**
 * Represents a user-defined set of dice configurations.
 * This entity is stored in the "dice_sets" table in the database.
 *
 * @property id The unique identifier for the dice set. Auto-generated by the database.
 * @property name The user-defined name for this dice set.
 * @property diceConfigs A list of [DiceConfig] objects defining the dice in this set.
 *                      Stored as a JSON string in the database using [DiceConfigListConverter].
 * @property isFavorite A boolean flag indicating whether this dice set is marked as a favorite by the user.
 * @property createdAt A timestamp string indicating when this dice set was created.
 *                     Defaults to the current timestamp when inserted into the database.
 */
@Entity(tableName = "dice_sets")
@TypeConverters(DiceConfigListConverter::class)
data class DiceSet(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    var name: String,
    @ColumnInfo(name = "dice_configs")
    var diceConfigs: List<DiceConfig>,
    @ColumnInfo(name = "is_favorite")
    var isFavorite: Boolean = false,
    @ColumnInfo(name = "created_at", defaultValue = "CURRENT_TIMESTAMP")
    var createdAt: String? = null
) {
    /**
     * A summary string displaying the configurations of all dice in this set.
     * For example: "2 x D6, 1 x D20".
     */
    val summaryDisplay: String
        get() = diceConfigs.joinToString(", ") { it.displayConfig }
}